spring:
  datasource:
    url: jdbc:mysql://db-java-study-02.c9brofv98azn.ap-northeast-3.rds.amazonaws.com:3306/hellospring
    username: admin
    password: ppppaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
server:
  port: 58080
