spring:
  datasource:
    url: jdbc:mysql://localhost:53306/hellospring
    username: develop
    password: develop
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
server:
  port: 58080
